[tool.pylint.messages_control]
disable = "C0330, C0326, E0401"

[tool.pylint.format]
max-line-length = "120"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''