defaults:
  - scenarios:
    - metron_trivial_scenario
  - isaac_sim@isaac_sim # do not touch
  - writer@writer

settings:
  ov_nucleus_ip: localhost
  issac_sim_version: 2022.2.0
  ardagen_extension:
    name: metron.ai.ardagen
    fs_path: ???