defaults:
  - scenarios:
    - dummy_scenario
  - isaac_sim@isaac_sim # do not touch
  - writer@writer

settings:
  ov_nucleus_ip: localhost
  issac_sim_version: 5.0
  ardagen_extension:
    name: metron.ai.ardagen
    fs_path: ???