_target_: tools.single_camera.SingleCamera # do not touch
position:
  - ???
  - ???
  - ???
rotation:
  - ???
  - ???
  - ???
clipping_range:
  - ???
  - ???
resolution:
  - ??? # width
  - ??? # height