_target_: tools.single_camera.SingleCamera # do not touch
position:
  - ??? # world coordinate x
  - ??? # world coordinate y
  - ??? # world coordinate z
rotation:
  - ??? # degrees x
  - ??? # degrees y
  - ??? # degrees z
clipping_range:
  - ???
  - ???
resolution:
  - ??? # width
  - ??? # height