ov_blue_container_assets:
  _target_: synthesizers.synth_workers.assets_synths.ov_assets_synthesizer.OVAssetsSynthesizer # do not touch
  usds:
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f03/container_f03.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f04/container_f04.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f05/container_f05.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f08/container_f08.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f09/container_f09.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f010/container_010.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f013/container_013.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f014/container_014.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f015/container_015.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f016/container_016.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f017/container_017.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f018/container_018.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f020/container_020.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f021/container_021.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f023/container_023.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f024/container_024.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f026/container_026.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f027/container_027.usd