ov_blue_container_assets:
  _target_: synthesizers.synth_workers.assets_synths.ov_assets_synthesizer.OVAssetsSynthesizer # do not touch
  usds:
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f03/container_f03.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f04/container_f04.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f05/container_f05.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f08/container_f08.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f09/container_f09.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f10/container_f10.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f13/container_f13.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f14/container_f14.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f15/container_f15.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f16/container_f16.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f17/container_f17.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f18/container_f18.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f20/container_f20.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f21/container_f21.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f23/container_f23.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f24/container_f24.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f26/container_f26.usd
    - omniverse://${settings.ov_nucleus_ip}/NVIDIA/Assets/simready_content/common_assets/props/container_f27/container_f27.usd